### ISSUE TITLE
Scrollbar hit area does not extend to the window edge

### ISSUE THREAD

**Issue by Timmmm** [atom/one-dark-ui#181]
Hi, this issue was [originally reported for Atom](https://github.com/atom/atom/issues/8298) but it looks like lodev09 never got around to reporting it here. The linked issue has a good description so I won't repeat it here. I'll just add that the Atom Light/Dark themes behave correctly so should be possibly to fix by copying them.

**Comment by 50Wliu** [comment]
This has already been fixed and will be available starting in Atom 1.13-beta.

**Comment by syntaxaire** [comment]
Not sure if this was never fixed or if it regressed. On Atom 1.16.0 with the included One Dark UI theme active, the scrollbar is not at the edge of the window.

This is most easily reproduced by going fullscreen with F11 and putting the mouse cursor to the right edge. You have to edge the mouse left again by about a dozen pixels before you get the scrollbar. Reproduced on both Windows 10 and KDE/Ubuntu.

**Comment by simurai** [comment]
@syntaxaire For Atom `1.16`. In the theme settings, there is a layout mode. Switching it to "Compact" should fix this issue.

![screen shot 2017-04-22 at 11 08 20 am](https://cloud.githubusercontent.com/assets/378023/25300521/0d6a6f62-274c-11e7-84e4-d91399856c79.png)

Then for Atom `1.17` it will be compact by default, but there is a `1px` hover area on the sides for the docks toggle button. You will be able remove it with the "Hide docks toggle buttons" option:

![screen shot 2017-04-22 at 11 10 36 am](https://cloud.githubusercontent.com/assets/378023/25300546/83428940-274c-11e7-97f2-4dec0611772e.png)

**Comment by syntaxaire** [comment]
That's helpful, but it still doesn't move the scroll bar to the edge in full screen mode, which violates a fundamental principle in UI design: an element drawn at the edge of the screen should be accessible by moving your mouse to the edge of the screen.

Actually, it reveals another bug as well: If you grab the scroll bar in fullscreen mode then move it up and down, Atom will scroll smoothly if the cursor is in the open but will scroll with janky half-second pauses if the cursor is against the edge of the screen. This might be related to the way the cursor icon flickers between "pointer" and "hand" constantly if you just move it up and down the right hand side of the screen in full screen mode without clicking anything.

**Comment by simurai** [comment]
> @syntaxaire it still doesn't move the scroll bar to the edge in full screen mode

What's your OS and current [Atom version](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?

**Comment by syntaxaire** [comment]
Sorry, should have specified.
```
Atom: 1.16.0 x64
Electron: 1.3.13
OS: Ubuntu 17.04
```
